# https://taskfile.dev

version: '3'

tasks:
  all:
  - task: clean
  - task: format
  - task: build
  - task: test
  - task: pack
  - task: install

  build:
    cmds:
    - dotnet build src --configuration Release

  test:
    cmds:
    - dotnet test tests

  format:
    cmds:
    - dotnet format src

  pack:
    deps:
    - build
    cmds:
    - powershell cp -Recurse -Force src/bin/Release/net462/ .\dist\raw\
    - ~/AppData/Local/Playnite/Toolbox.exe pack src/bin/Release/net462/ dist
    # - powershell mv ./dist/*.pext

  clean:
    cmds:
    - powershell -command "Remove-Item -Force -Recurse .\dist -ErrorAction Ignore" || true
    - powershell -command "Remove-Item -Force -Recurse .\src\bin\ -ErrorAction Ignore" || true

  install:
    cmds:
    - powershell ./dist/*.pext

  logs:
    cmds:
    - powershell "Get-Content ~/Appdata/Roaming/Playnite/extensions.log" -Wait

  settings:
    cmds:
    - powershell "~/Appdata/Roaming/Playnite/ExtensionsData/c038558e-427b-4551-be4c-be7009ce5a8d/config.json"

  download-game-test-data:
    cmds:
    - | 
      "{{.USERPROFILE}}\scoop\shims\curl.exe" \
        -H "Content-Type: application/x-www-form-urlencoded" \
        -H "Accept: application/json" \
        "https://www.pcgamingwiki.com/w/api.php?action=parse&format=json&page=Assassin's_Creed_Chronicles:_India" > test.json